version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/before_script.sh   # Make sure the path is correct
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/after_script.sh
      timeout: 300
      runas: root
